---
  - hosts: slave1
    become: yes
    name: Installing apache2 on slave1
    tasks:
     - name: Install apache2
       apt: name=apache2 state=latest

  - hosts: slave2
    become: yes
    name: Installing nginx on slave2
    tasks:
     - name: installing nginx
       apt: name=nginx state=latest

# Executing scripts using Ansible Playbook
# sudo nano script.sh
# echo “hello world” > /var/www/html/1.html

---
  - hosts: slave1
    become: yes
    name: Installing apache2 on slave1
    tasks:
     - name: Install apache2
       apt: name=apache2 state=latest
  
  - hosts: slave2
    become: yes
    name: Installing nginx on slave2
    tasks:
     - name: installing nginx
       apt: name=nginx state=latest
     - name: Running a script
       script: script.sh

# $ ansible-playbook play.yml
